name: push-to-integral-repo
on:
  push:
    branches: [mi_dev]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Setup Env
        run: |
          git clone https://github.com/ingydotnet/git-subrepo /opt/git-subrepo 
          echo 'source /opt/git-subrepo/.rc' >> ~/.bashrc
          git clone git@github.com:rel4team/mi-dev-integral-rel4.git
          cd mi-dev-integral-rel4
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          INTEGRAL_COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -n 1)
          echo "INTEGRAL_COMMIT_MESSAGE=${INTEGRAL_COMMIT_MESSAGE}" >> $GITHUB_ENV
      - name: Push To Integral Repo
        if: ${{! contains(github.event.head_commit.message,'git subrepo') }}
        env:
          CURRENT_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          echo "current repo commit message: $CURRENT_COMMIT_MESSAGE"
          echo "integral repo commit message: $INTEGRAL_COMMIT_MESSAGE"
          if echo "$CURRENT_COMMIT_MESSAGE" | grep -q -E "$INTEGRAL_COMMIT_MESSAGE" || echo "$INTEGRAL_COMMIT_MESSAGE" | grep -q -E "$CURRENT_COMMIT_MESSAGE"; then
            echo "sync finished"
          else
            echo "prepare sync"
            source /opt/git-subrepo/.rc
            cd mi-dev-integral-rel4
            git subrepo pull --all
            git push   
          fi

