#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

# Match the rust toolchain with that in the rust-sel4 repository for best results.

[toolchain]
channel = "nightly-2024-02-01"
components = [ "rustfmt", "rust-src" ]
targets = [
    "riscv64imac-unknown-none-elf",
    "aarch64-unknown-none-softfloat"
]
